### ISSUE TITLE
Plugin failed to launch

### ISSUE THREAD

**Issue by hellotinh03** [Vital7/GameRemover#48]
```
2022-01-28 06:35:27|ArchiSteamFarm-19|ERROR|ASF|InitPlugins() Failed due to error: GameRemover, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null
2022-01-28 06:35:27|ArchiSteamFarm-19|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'ArchiSteamFarm, Version=5.2.2.2, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Could not load file or assembly 'ArchiSteamFarm, Version=5.2.2.2, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule )
   at System.Reflection.RuntimeModule.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.IO.FileNotFoundException: Could not load file or assembly 'ArchiSteamFarm, Version=5.2.2.2, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'ArchiSteamFarm, Version=5.2.2.2, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'ArchiSteamFarm, Version=5.2.2.2, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'ArchiSteamFarm, Version=5.2.2.2, Culture=neutral, PublicKeyToken=null'
```

I'm using Docker version of ASF

**Comment by Vital7** [comment]
Hi, can I ask you to attach full `log.txt` file?

**Comment by Hellix3** [comment]
> Hi, can I ask you to attach full `log.txt` file?

У меня такая же проблема

2022-03-28 22:49:34|ArchiSteamFarm-2816|INFO|ASF|InitCore() ArchiSteamFarm V5.2.3.7 (win-x64/2594b264-7ca8-477c-a5b8-6612c4555831 | .NET 6.0.2; win10-x64; Microsoft Windows 10.0.19043)
2022-03-28 22:49:34|ArchiSteamFarm-2816|INFO|ASF|InitCore() Copyright © 2015-2022 JustArchiNET
2022-03-28 22:49:35|ArchiSteamFarm-2816|INFO|ASF|WarnAboutIncompleteTranslation() ASF will attempt to use your preferred ru-UA (Russian (Ukraine)) culture, but translation into that language is only 0,0 % complete. Perhaps you could help us improve the ASF translation for your language?
2022-03-28 22:49:35|ArchiSteamFarm-2816|INFO|ASF|InitPlugins() Initializing Plugins...
2022-03-28 22:49:35|ArchiSteamFarm-2816|ERROR|ASF|InitPlugins() Failed due to error: GameRemover, Version=2.1.0.0, Culture=neutral, PublicKeyToken=null
2022-03-28 22:49:35|ArchiSteamFarm-2816|ERROR|ASF|InitPlugins() System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule )
   at System.Reflection.RuntimeModule.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.TypeLoadException
2022-03-28 22:49:45|ArchiSteamFarm-2816|INFO|ASF|UpdateAndRestart() ASF will automatically check for new versions every один день.
2022-03-28 22:49:45|ArchiSteamFarm-2816|INFO|ASF|Update() Checking for new version...
2022-03-28 22:49:46|ArchiSteamFarm-2816|INFO|ASF|Update() Local version: 5.2.3.7 | Remote version: 5.2.3.7
2022-03-28 22:49:46|ArchiSteamFarm-2816|INFO|ASF|StartInteractiveConsole() Interactive console is now active, type 'c' in order to enter command mode.
2022-03-28 22:49:46|ArchiSteamFarm-2816|INFO|ASF|Start() Starting IPC server...
2022-03-28 22:49:47|ArchiSteamFarm-2816|INFO|ASF|Start() IPC server ready!
2022-03-28 22:49:47|ArchiSteamFarm-2816|INFO|bot1|Start() Starting...
2022-03-28 22:49:47|ArchiSteamFarm-2816|INFO|bot1|Connect() Connecting...
2022-03-28 22:49:47|ArchiSteamFarm-2816|INFO|bot1|OnConnected() Connected to Steam!
2022-03-28 22:49:47|ArchiSteamFarm-2816|INFO|bot1|OnConnected() Logging in...
2022-03-28 22:49:48|ArchiSteamFarm-2816|INFO|bot1|OnLoggedOn() Successfully logged on
2022-03-28 22:49:48|ArchiSteamFarm-2816|INFO|bot1|Init() Logging in to ISteamUserAuth...
2022-03-28 22:49:50|ArchiSteamFarm-2816|INFO|bot1|Init() Success!
2022-03-28 22:49:51|ArchiSteamFarm-2816|INFO|bot1|IsAnythingToFarm() Checking first badge page...
2022-03-28 22:49:51|ArchiSteamFarm-2816|INFO|bot1|StartFarming() We don't have anything to farm on this account!

**Comment by Vital7** [comment]
Should be working now, please test it when ASF v5.2.5.5 releases (since new version of plugin is compatible only since that version)
I'll close this issue, if it still happens after that update - feel free to reopen!
